content = open('app/(dashboard)/admin/companions/[id]/page.tsx', encoding='utf-8').read()
content = content.replace('import { createClient } from "@/lib/supabase/server";', 'import { createClient, createAdminClient } from "@/lib/supabase/server";')
content = content.replace('if (adminProfile?.role !== "admin") redirect("/login");\r\n', 'if (adminProfile?.role !== "admin") redirect("/login");\r\n\r\n  const admin = createAdminClient();\r\n')
content = content.replace('await supabase\r\n    .from("companion_profiles")', 'await admin\r\n    .from("companion_profiles")')
content = content.replace('await supabase\r\n    .from("profiles")\r\n    .select("*")', 'await admin\r\n    .from("profiles")\r\n    .select("*")')
content = content.replace('await supabase\r\n    .from("companion_references")', 'await admin\r\n    .from("companion_references")')
content = content.replace('await supabase\r\n    .from("companion_status_history")', 'await admin\r\n    .from("companion_status_history")')
open('app/(dashboard)/admin/companions/[id]/page.tsx', 'w', encoding='utf-8').write(content)
print('Done')
