data = open('app/(dashboard)/admin/companions/[id]/page.tsx', encoding='utf-8').read()
data = data.replace('import { createClient } from "@/lib/supabase/server";', 'import { createClient, createAdminClient } from "@/lib/supabase/server";')
data = data.replace('if (adminProfile?.role !== "admin") redirect("/login");', 'if (adminProfile?.role !== "admin") redirect("/login");\r\n\r\n  const admin = createAdminClient();')
data = data.replace('await supabase\r\n    .from("companion_profiles")', 'await admin\r\n    .from("companion_profiles")')
data = data.replace('await supabase\r\n    .from("profiles")\r\n    .select("*")', 'await admin\r\n    .from("profiles")\r\n    .select("*")')
data = data.replace('await supabase\r\n    .from("companion_references")', 'await admin\r\n    .from("companion_references")')
data = data.replace('await supabase\r\n    .from("companion_status_history")', 'await admin\r\n    .from("companion_status_history")')
open('app/(dashboard)/admin/companions/[id]/page.tsx', 'w', encoding='utf-8').write(data)
print('Done')
